"""Runtime lookups for the offline-calibrated strength/equity tables.

`evaluate_relative_strength` returns a fast 0..1 heuristic score, not a win
probability, and it is blind to how many opponents are still in the hand. Comparing
that score directly against pot odds -- as the strategy used to -- compares two
different quantities. These tables map the score onto measured equity by street and
opponent count, at dictionary-lookup cost.

If the generated tables are missing the lookups degrade to the identity, which
reproduces the previous behaviour rather than breaking the agent.
"""
from __future__ import annotations

from .cards import Card, RV

try:  # generated by scratch/build_calibration.py
    from .calibration_data import BINS, PREFLOP_PERCENTILE, POSTFLOP_EQUITY
except Exception:  # pragma: no cover
    BINS = 0
    PREFLOP_PERCENTILE: dict[str, float] = {}
    POSTFLOP_EQUITY: dict[str, list[float]] = {}

_OPPONENT_KEYS = (1, 2, 3, 4, 5)


def hand_class(hero: list[Card]) -> str:
    """Canonical 169-bucket name for a two-card holding, e.g. 'AKs', 'QQ', 'T9o'."""
    a, b = sorted((hero[0].rank, hero[1].rank), reverse=True)
    r1 = next(r for r, v in RV.items() if v == a)
    r2 = next(r for r, v in RV.items() if v == b)
    suited = hero[0].suit == hero[1].suit
    return r1 + r2 + ("s" if suited and a != b else "o")


def preflop_percentile(hero: list[Card]) -> float | None:
    """Percentile of this starting hand among all 169 classes (1.0 = strongest).

    This is what makes a VPIP target meaningful: "play the top X% of hands" becomes a
    direct comparison instead of a guess at a threshold on an uncalibrated score.
    """
    if len(hero) != 2 or not PREFLOP_PERCENTILE:
        return None
    return PREFLOP_PERCENTILE.get(hand_class(hero))


def strength_to_equity(street: int, opponents: int, strength: float) -> float:
    """Map a heuristic postflop strength onto measured equity vs `opponents` hands."""
    if not POSTFLOP_EQUITY or street < 3:
        return strength
    n = min(_OPPONENT_KEYS[-1], max(_OPPONENT_KEYS[0], int(opponents)))
    table = POSTFLOP_EQUITY.get(f"{street}:{n}")
    if not table:
        return strength
    idx = int(strength * BINS)
    if idx < 0:
        idx = 0
    elif idx >= BINS:
        idx = BINS - 1
    return table[idx]


def has_tables() -> bool:
    return bool(PREFLOP_PERCENTILE) and bool(POSTFLOP_EQUITY)
