"""Canonical construction of the tournament context the strategy conditions on.

`StrategyAgent._tournament_pressure` reads rank / bb100 / stage / boundaries /
hands remaining, and those values steer safety, attack, bubble and late-stage
behaviour across all three tournament stages:
- Preliminary: 120 players, 10 rounds x 20 hands = 200 hands, Target: Top 12 (10%)
- Semifinal: 12 players, 2 tables of 6, 20 hands, Target: Top 3 per table (50%)
- Final: 6 players, 1 table of 6, 30 hands, Target: 1st Place Champion (16.7%)
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
import math
from typing import Any

try:  # generated by scratch/build_context_ladder.py
    from .context_data import RANK_LADDER, GOLDEN_LINE_BB100
except Exception:  # pragma: no cover - fallback keeps the agent usable without the table
    RANK_LADDER: list[tuple[float, int]] = [
        (-1e9, 120),
        (-40.0, 105),
        (-15.0, 85),
        (0.0, 60),
        (12.0, 32),
        (20.0, 20),
        (25.0, 13),
        (28.0, 12),
        (45.0, 6),
        (80.0, 1),
        (1e9, 1),
    ]
    GOLDEN_LINE_BB100 = 28.0

FIELD_SIZE = 120
QUALIFY_RANK = 12


@dataclass(slots=True)
class TournamentContext:
    """Explicit, structured representation of tournament state for policy decisions."""
    stage: str
    rank: int | None
    bb100: float | None
    hands_remaining: int
    total_stage_hands: int
    stage_progress: float
    round_no: int
    target_rank: int
    cutoff_bb100: float | None
    buffer_bb100: float | None
    table_strength: float = 0.0
    rank12_bb100: float | None = None
    rank13_bb100: float | None = None
    rank3_bb100: float | None = None
    rank4_bb100: float | None = None
    leader_bb100: float | None = None
    second_bb100: float | None = None
    rank1_bb100: float | None = None
    rank2_bb100: float | None = None
    cycle_no: int | None = None
    extra: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "stage": self.stage,
            "rank": self.rank,
            "bb100": self.bb100,
            "hands_remaining": self.hands_remaining,
            "total_stage_hands": self.total_stage_hands,
            "stage_progress": self.stage_progress,
            "round_no": self.round_no,
            "target_rank": self.target_rank,
            "cutoff_bb100": self.cutoff_bb100,
            "buffer_bb100": self.buffer_bb100,
            "table_strength": self.table_strength,
            "rank12_bb100": self.rank12_bb100,
            "rank13_bb100": self.rank13_bb100,
            "rank3_bb100": self.rank3_bb100,
            "rank4_bb100": self.rank4_bb100,
            "leader_bb100": self.leader_bb100,
            "second_bb100": self.second_bb100,
            "rank1_bb100": self.rank1_bb100,
            "rank2_bb100": self.rank2_bb100,
        }
        if self.cycle_no is not None:
            d["cycle_no"] = self.cycle_no
        if self.extra:
            d.update(self.extra)
        return d


def rank_from_bb100(bb100: float) -> int:
    """Implied field rank for a given BB/100, from the calibrated ladder."""
    if not RANK_LADDER:
        return FIELD_SIZE
    pts = RANK_LADDER
    if bb100 <= pts[0][0]:
        return int(pts[0][1])
    if bb100 >= pts[-1][0]:
        return int(pts[-1][1])
    for i in range(1, len(pts)):
        x0, y0 = pts[i - 1]
        x1, y1 = pts[i]
        if bb100 <= x1:
            if x1 == x0:
                return int(round(y1))
            t = (bb100 - x0) / (x1 - x0)
            return int(round(y0 + t * (y1 - y0)))
    return int(pts[-1][1])


def boundary_bb100(rank: int) -> float:
    """BB/100 at which the ladder places an agent at `rank` (inverse of rank_from_bb100)."""
    if not RANK_LADDER:
        return GOLDEN_LINE_BB100
    pts = RANK_LADDER
    for i in range(len(pts) - 1, -1, -1):
        if int(pts[i][1]) <= rank:
            return float(pts[i][0])
    return float(pts[0][0])


def build_context(
    rank: Any,
    bb100: Any,
    rank12_bb100: Any = None,
    rank13_bb100: Any = None,
    hands_remaining: Any = 50,
    round_no: Any = 1,
    cycle_no: Any = None,
    table_strength: float = 0.0,
    stage: str | None = None,
    target_rank: int | None = None,
    total_stage_hands: int | None = None,
    rank3_bb100: Any = None,
    rank4_bb100: Any = None,
    leader_bb100: Any = None,
    second_bb100: Any = None,
    rank1_bb100: Any = None,
    rank2_bb100: Any = None,
    **kwargs: Any,
) -> dict[str, Any]:
    """Unified canonical construction of tournament context dict with stage awareness."""
    r_no = int(round_no) if round_no is not None else 1

    # Infer stage if not explicitly passed
    if stage is None:
        if r_no == 11:
            stage = "semifinal"
        elif r_no == 12:
            stage = "final"
        else:
            stage = "preliminary"

    # Stage-specific defaults
    if stage == "semifinal":
        t_rank = target_rank if target_rank is not None else 3
        tot_hands = total_stage_hands if total_stage_hands is not None else 20
        cutoff = rank4_bb100 if rank is not None and int(rank) <= 3 else rank3_bb100
    elif stage == "final":
        t_rank = target_rank if target_rank is not None else 1
        tot_hands = total_stage_hands if total_stage_hands is not None else 30
        c1 = leader_bb100 if leader_bb100 is not None else rank1_bb100
        c2 = second_bb100 if second_bb100 is not None else rank2_bb100
        cutoff = c2 if rank is not None and int(rank) == 1 else c1
    else:
        stage = "preliminary"
        t_rank = target_rank if target_rank is not None else QUALIFY_RANK
        tot_hands = total_stage_hands if total_stage_hands is not None else 200
        cutoff = rank13_bb100 if rank is not None and int(rank) <= QUALIFY_RANK else rank12_bb100

    rem = max(0, int(hands_remaining)) if hands_remaining is not None else 0
    progress = max(0.0, min(1.0, 1.0 - (rem / max(1, tot_hands))))

    buf: float | None = None
    if bb100 is not None and cutoff is not None:
        try:
            buf = float(bb100) - float(cutoff)
        except (TypeError, ValueError):
            buf = None

    t_ctx = TournamentContext(
        stage=stage,
        rank=int(rank) if rank is not None else None,
        bb100=float(bb100) if bb100 is not None else None,
        hands_remaining=rem,
        total_stage_hands=tot_hands,
        stage_progress=progress,
        round_no=r_no,
        target_rank=t_rank,
        cutoff_bb100=float(cutoff) if cutoff is not None else None,
        buffer_bb100=buf,
        table_strength=float(table_strength or 0.0),
        rank12_bb100=rank12_bb100,
        rank13_bb100=rank13_bb100,
        rank3_bb100=rank3_bb100,
        rank4_bb100=rank4_bb100,
        leader_bb100=leader_bb100,
        second_bb100=second_bb100,
        rank1_bb100=rank1_bb100 if rank1_bb100 is not None else leader_bb100,
        rank2_bb100=rank2_bb100 if rank2_bb100 is not None else second_bb100,
        cycle_no=cycle_no,
        extra=kwargs,
    )
    return t_ctx.to_dict()


def build_preliminary_context(
    rank: int | None,
    bb100: float | None,
    rank12_bb100: float | None,
    rank13_bb100: float | None,
    hands_remaining: int,
    round_no: int,
    table_strength: float = 0.0,
    cycle_no: int | None = None,
) -> dict[str, Any]:
    return build_context(
        rank=rank,
        bb100=bb100,
        rank12_bb100=rank12_bb100,
        rank13_bb100=rank13_bb100,
        hands_remaining=hands_remaining,
        round_no=round_no,
        cycle_no=cycle_no,
        table_strength=table_strength,
        stage="preliminary",
        target_rank=12,
        total_stage_hands=200,
    )


def build_semifinal_context(
    rank: int | None,
    bb100: float | None,
    rank3_bb100: float | None,
    rank4_bb100: float | None,
    hands_remaining: int,
    table_strength: float = 0.0,
) -> dict[str, Any]:
    return build_context(
        rank=rank,
        bb100=bb100,
        hands_remaining=hands_remaining,
        round_no=11,
        table_strength=table_strength,
        stage="semifinal",
        target_rank=3,
        total_stage_hands=20,
        rank3_bb100=rank3_bb100,
        rank4_bb100=rank4_bb100,
    )


def build_final_context(
    rank: int | None,
    bb100: float | None,
    leader_bb100: float | None,
    second_bb100: float | None,
    hands_remaining: int,
    table_strength: float = 0.0,
) -> dict[str, Any]:
    return build_context(
        rank=rank,
        bb100=bb100,
        hands_remaining=hands_remaining,
        round_no=12,
        table_strength=table_strength,
        stage="final",
        target_rank=1,
        total_stage_hands=30,
        leader_bb100=leader_bb100,
        second_bb100=second_bb100,
        rank1_bb100=leader_bb100,
        rank2_bb100=second_bb100,
    )


def synthetic_context(bb100: float, hands_remaining: int, round_no: int,
                      cycle_no: int | None = None, table_strength: float = 0.0) -> dict[str, Any]:
    """Context derived from the agent's own win rate, for when standings are unavailable."""
    rank = rank_from_bb100(bb100)
    return build_context(
        rank=rank,
        bb100=bb100,
        rank12_bb100=boundary_bb100(QUALIFY_RANK),
        rank13_bb100=boundary_bb100(QUALIFY_RANK + 1),
        hands_remaining=max(0, int(hands_remaining)),
        round_no=round_no,
        cycle_no=cycle_no,
        table_strength=table_strength,
    )


def context_from_standings(rows: list[dict[str, Any]], hero_id: str | None,
                           hands_remaining: int, round_no: int,
                           cycle_no: int | None = None) -> dict[str, Any] | None:
    """Build the context from real competition standings, if they carry what we need."""
    parsed: list[tuple[str, float]] = []
    for r in rows or []:
        if not isinstance(r, dict):
            continue
        aid = r.get("agentId") or r.get("id") or (r.get("agent") or {}).get("agentId")
        val = r.get("bb100")
        if val is None:
            bb = r.get("bb")
            hands = r.get("hands")
            if bb is not None and hands:
                val = float(bb) / float(hands) * 100.0
        if aid is None or val is None:
            continue
        try:
            parsed.append((str(aid), float(val)))
        except (TypeError, ValueError):
            continue
    if len(parsed) < QUALIFY_RANK:
        return None
    parsed.sort(key=lambda x: -x[1])
    rank = next((i for i, (aid, _) in enumerate(parsed, 1) if aid == hero_id), None)
    if rank is None:
        return None
    r12 = parsed[QUALIFY_RANK - 1][1]
    r13 = parsed[QUALIFY_RANK][1] if len(parsed) > QUALIFY_RANK else r12
    return build_context(rank, parsed[rank - 1][1], r12, r13, hands_remaining, round_no, cycle_no)
