"""Canonical construction of the tournament context the strategy conditions on.

`StrategyAgent._tournament_pressure` reads rank / bb100 / the rank-12 and rank-13
boundaries / hands remaining, and those values steer safety, attack, bubble and
late-stage behaviour. The simulator used to synthesise that signal from real standings
while live play synthesised it from a five-bucket hardcoded ladder pinned to invented
20.0 / 15.0 golden lines. A policy trained on one distribution and deployed on another
is being graded against a signal it never saw, so both paths now go through here.
"""
from __future__ import annotations

from typing import Any

try:  # generated by scratch/build_context_ladder.py
    from .context_data import RANK_LADDER, GOLDEN_LINE_BB100
except Exception:  # pragma: no cover - fallback keeps the agent usable without the table
    RANK_LADDER: list[tuple[float, int]] = [
        (-1e9, 120),
        (-40.0, 105),
        (-15.0, 85),
        (0.0, 60),
        (12.0, 32),
        (20.0, 20),
        (25.0, 13),
        (28.0, 12),
        (45.0, 6),
        (80.0, 1),
        (1e9, 1),
    ]
    GOLDEN_LINE_BB100 = 28.0

FIELD_SIZE = 120
QUALIFY_RANK = 12


def rank_from_bb100(bb100: float) -> int:
    """Implied field rank for a given BB/100, from the calibrated ladder.

    Piecewise linear between breakpoints, clamped at both ends. Monotone decreasing:
    a higher win rate never yields a worse rank.
    """
    if not RANK_LADDER:
        return FIELD_SIZE
    pts = RANK_LADDER
    if bb100 <= pts[0][0]:
        return int(pts[0][1])
    if bb100 >= pts[-1][0]:
        return int(pts[-1][1])
    for i in range(1, len(pts)):
        x0, y0 = pts[i - 1]
        x1, y1 = pts[i]
        if bb100 <= x1:
            if x1 == x0:
                return int(round(y1))
            t = (bb100 - x0) / (x1 - x0)
            return int(round(y0 + t * (y1 - y0)))
    return int(pts[-1][1])


def boundary_bb100(rank: int) -> float:
    """BB/100 at which the ladder places an agent at `rank` (inverse of rank_from_bb100)."""
    if not RANK_LADDER:
        return GOLDEN_LINE_BB100
    pts = RANK_LADDER
    for i in range(len(pts) - 1, -1, -1):
        if int(pts[i][1]) <= rank:
            return float(pts[i][0])
    return float(pts[0][0])


def build_context(rank: Any, bb100: Any, rank12_bb100: Any, rank13_bb100: Any,
                  hands_remaining: Any, round_no: Any, cycle_no: Any = None,
                  table_strength: float = 0.0) -> dict[str, Any]:
    """The single definition of the tournament context dict."""
    ctx = {
        "rank": rank,
        "bb100": bb100,
        "rank12_bb100": rank12_bb100,
        "rank13_bb100": rank13_bb100,
        "hands_remaining": hands_remaining,
        "round_no": round_no,
        "table_strength": float(table_strength or 0.0),
    }
    if cycle_no is not None:
        ctx["cycle_no"] = cycle_no
    return ctx


def synthetic_context(bb100: float, hands_remaining: int, round_no: int,
                      cycle_no: int | None = None, table_strength: float = 0.0) -> dict[str, Any]:
    """Context derived from the agent's own win rate, for when standings are unavailable.

    Uses the same ladder the simulator's ranks were calibrated against, so the values
    the live agent sees occupy the same range as the ones it was trained on.
    """
    rank = rank_from_bb100(bb100)
    return build_context(
        rank=rank,
        bb100=bb100,
        rank12_bb100=boundary_bb100(QUALIFY_RANK),
        rank13_bb100=boundary_bb100(QUALIFY_RANK + 1),
        hands_remaining=max(0, int(hands_remaining)),
        round_no=round_no,
        cycle_no=cycle_no,
        table_strength=table_strength,
    )


def context_from_standings(rows: list[dict[str, Any]], hero_id: str | None,
                           hands_remaining: int, round_no: int,
                           cycle_no: int | None = None) -> dict[str, Any] | None:
    """Build the context from real competition standings, if they carry what we need.

    Returns None when the payload does not contain a usable bb100 ranking, so callers
    can fall back to `synthetic_context` instead of inventing a rank.
    """
    parsed: list[tuple[str, float]] = []
    for r in rows or []:
        if not isinstance(r, dict):
            continue
        aid = r.get("agentId") or r.get("id") or (r.get("agent") or {}).get("agentId")
        val = r.get("bb100")
        if val is None:
            bb = r.get("bb")
            hands = r.get("hands")
            if bb is not None and hands:
                val = float(bb) / float(hands) * 100.0
        if aid is None or val is None:
            continue
        try:
            parsed.append((str(aid), float(val)))
        except (TypeError, ValueError):
            continue
    if len(parsed) < QUALIFY_RANK:
        return None
    parsed.sort(key=lambda x: -x[1])
    rank = next((i for i, (aid, _) in enumerate(parsed, 1) if aid == hero_id), None)
    if rank is None:
        return None
    r12 = parsed[QUALIFY_RANK - 1][1]
    r13 = parsed[QUALIFY_RANK][1] if len(parsed) > QUALIFY_RANK else r12
    return build_context(rank, parsed[rank - 1][1], r12, r13, hands_remaining, round_no, cycle_no)
